# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20160416_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='healthprogram',
            name='sessions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
