# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20160416_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='healh_program_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
