# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_attendance_healh_program_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='healh_program_id',
            new_name='health_program_id',
        ),
    ]
